name: Build and Release

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v1.3.1

    - name: Restore NuGet packages
      run: nuget restore ${{ vars.SOLUTION }}

    - name: Build Solution
      run: msbuild.exe ${{ vars.SOLUTION }} /p:Configuration=Release /p:Platform="Any CPU" /p:TargetFrameworkVersion=v4.7.2

    - name: Create Zip Archive
      shell: powershell
      run: |
        $tag = "$env:GITEA_REF_NAME"
        $archiveName = "converter-$tag.zip"
        mkdir release
        $source = ".\hostexecutor\bin\Release\*"
        $destination = ".\release"
        xcopy "$source" "$destination" /E /H /Y
        Compress-Archive -Path "$destination\*" -DestinationPath "$archiveName"

    - name: Upload to Release
      env:
        GITEA_TOKEN: ${{ secrets.TOKEN }}
      shell: powershell
      run: |
        $tag = "$env:GITEA_REF_NAME"
        $fileName = ".\converter-$tag.zip"
        $repo = "${{ gitea.repository }}"
        $gitea_url = "${{ vars.URL }}"
        $apiUrl = "$gitea_url/api/v1/repos/$repo/releases/tags/$tag/assets?name=$fileName"
        
        if(-Not (Test-Path $fileName)) {
            throw "Archive file $fileName not found!"
        }
        
        curl -X POST `
          -H "Authorization: token $env:GITEA_TOKEN" `
          -H "Content-Type: application/zip" `
          --data-binary "@$fileName" `
          $apiUrl