name: Build and Release

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v1.3.1

    - name: Restore NuGet packages
      run: nuget restore ${{ vars.SOLUTION }}

    - name: Build Solution
      run: msbuild.exe ${{ vars.SOLUTION }} /p:Configuration=Release /p:Platform="Any CPU" /p:TargetFrameworkVersion=v4.7.2

    - name: Create Zip Archive
      shell: powershell
      run: |
        $tag = "${{ gitea.ref }}" -replace '^refs/tags/', ''
        Compress-Archive -Path ".\bin\Release\*" -DestinationPath "converter-$tag.zip"

    - name: Upload to Release
      env:
        GITEA_TOKEN: ${{ secrets.TOKEN }}
      shell: powershell
      run: |
        $ref = "${{ gitea.ref }}"
        $tag = $ref -replace '^refs/tags/', ''

        $fileName = "converter-$tag.zip"

        $repo = "${{ gitea.repository }}" # user/repo
        $owner, $name = $repo -split '/'

        # URL Gitea
        $base = "${{ vars.URL }}"

        $releaseInfo = Invoke-RestMethod -Headers @{ Authorization = "token $env:GITEA_TOKEN" } `
          -Uri "$base/api/v1/repos/$repo/releases/tags/$tag" `
          -Method Get

        $releaseId = $releaseInfo.id

        $apiUrl = "$base/api/v1/repos/$repo/releases/$releaseId/assets?name=$fileName"

        curl -s -X POST -H "Authorization: token $GITEA_TOKEN" -F "attachment=@$fileName" $apiUrl
