name: Build and Release

on:
  push:
    tags:
      - '*'

env:
  PROJECT_PATH: Converter.csproj
  BUILD_CONFIGURATION: Release
  BUILD_PLATFORM: AnyCPU

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Add MSBuild to PATH
        uses: microsoft/setup-msbuild@v2

      - name: Restore NuGet packages
        run: nuget restore "${{ env.PROJECT_PATH }}"

      - name: Build Solution
        run: msbuild.exe "${{ env.PROJECT_PATH }}" /p:Configuration="${{ env.BUILD_CONFIGURATION }}" /p:Platform="${{ env.BUILD_PLATFORM }}" /p:TargetFrameworkVersion=v4.7.2

      - name: Create Zip Archive
        shell: powershell
        run: |
          $tag = "${{ github.ref_name }}"
          Compress-Archive -Path ".\bin\Release\*" -DestinationPath "converter-$tag.zip"

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: converter-${{ github.ref_name }}
          path: converter-${{ github.ref_name }}.zip

      - name: Upload to Release
        uses: softprops/action-gh-release@v2
        with:
          files: converter-${{ github.ref_name }}.zip
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
